apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-kart-orders-sm
  namespace: easy-kart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-kart-orders-sm #This should be same label
  template:
    metadata:
      labels:
        app: easy-kart-orders-sm #This should be same label
    spec:
      containers:
      - name: easy-kart-orders-sm
        image: pdesaidocker/easy-kart-api-orders-sm:{{imageTag}}
        resources:
          requests:
            memory: "128Mi"   # Minimum memory for the container to function
            cpu: "25m"       # Minimum CPU for the container to function
          limits:
            memory: "256Mi"   # Maximum memory that can be used
            cpu: "50m"       # Maximum CPU that can be used
        ports:
        - containerPort: 8080 #port defined in image dockerfile
        env:
        - name: ConnectionStrings__AzureServiceBus
          valueFrom:
             secretKeyRef:
                name: easy-kart-secret  
                key: azservicebusconnstr
     
